pull_request_rules:
  - name: Approve and merge non-major version dependabot upgrades
    conditions:
      - author~=^dependabot\[bot\]$
      - check-success~=lint
      - check-success~=build
      - check-success~=test
      - -dependabot-update-type = version-update:semver-major
    actions:
      review:
        type: APPROVE
      merge:
        method: squash

  - name: Approve and merge Snyk.io upgrades
    conditions:
      - author=isomeradmin
      - check-success~=lint
      - check-success~=build
      - check-success~=test
      - title~=^\[Snyk\]
      - base = develop
    actions:
      review:
        type: APPROVE
      merge:
        method: squash

  - name: Ping Isomer members for stale open PRs (>1 month since last activity)
    conditions:
      - updated-at<30 days ago
      - -closed
    actions:
      request_reviews:
        teams:
          - "@isomerpages/iso-engineers"
      comment:
        message: This pull request has been stale for more than 30 days! Could someone please take a look at it @isomerpages/iso-engineers

  - name: Automatically delete branches after they have been merged
    conditions:
      - merged
    actions:
      delete_head_branch:

  - name: Automatically mark a PR as draft if [WIP] is in the title
    conditions:
      - title~=(?i)\[wip\]
    actions:
      edit:
        draft: True
