[[headers]]
  for = "/*"
  [headers.values]
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "deny"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    Content-Security-Policy = "frame-ancestors 'none'"
[build]
  [build.environment]
    CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
    TERM = "xterm"
[[plugins]]
  package = "netlify-plugin-cypress"
  [plugins.inputs]
    # record the test results to cypress dashboard
    record = true
  [plugins.inputs.postBuild]
    # run tests after the deploy
    enable = true
    start = 'npm run ci'
